### ISSUE TITLE
SSH wrapper doesn't properly escape special characters

### ISSUE THREAD

**Issue by jnv** [cbetta/dokkufy#13]
I want to use `dokku` to setup ENV variables, for example:

```
dokku config:set SECRET_KEY='8l(3nkh$mids(%^y43api+dmulxtc#gc$5hm^31o+943b*s0t('
```

This however fails with: `sh: 1: Syntax error: "(" unexpected`

Looking at [Dokku class](https://github.com/cbetta/dokkufy/blob/d4267d6dae315d9a80b766aca92a21a65d9e4e42/lib/dokkufy/dokku.rb#L27), I suspect this is because special characters are not properly escaped/wrapped in.

Running the same command directly through SSH works, so the problem is not on Dokku's end.

**Comment by cbetta** [comment]
I decided to drop this functionality. For more details see #16
