### ISSUE TITLE
Can't pipe to dokku command

### ISSUE THREAD

**Issue by mtarnovan** [cbetta/dokkufy#14]
For example, this doesn't work with the dokku command provided by this gem:
`mysqldump foo | dokku mariadb:restore`
`Pseudo-terminal will not be allocated because stdin is not a terminal.`

This works as expected if I just alias the dokku command
`alias dokku='ssh dokku@dokku1'`

**Comment by cbetta** [comment]
I decided to drop this functionality. For more details see https://github.com/cbetta/dokkufy/pull/16
