### ISSUE TITLE
dokku run bundle exec rails console production not working

### ISSUE THREAD

**Issue by weirdobeaver** [cbetta/dokkufy#18]
When I try to  run dokku run bundle exec rails console production console is not showing. When I hit ctrl+d then I can exited console. I guess the issue here is that console is not sending live info.

I've checked and I'm using 0.1.6 version of gem that might be the problem.

**Comment by cbetta** [comment]
Hi the latest gem has removed this functionality. Please use one of the other toolsets for Dokku to do this instead.
